version: "3.7"

services:
    service-flow-vue:
        container_name: "service-flow-vue"
        build:
            context: .
            dockerfile: Dockerfile


        volumes:
            - ".:/app"
            - "/app/node_modules"
        ports:
        - "4000:4040"
        tty: true
        environment:
            - VUE_APP_KEYCLOAK_URL=${VUE_APP_KEYCLOAK_URL}
            - VUE_APP_KEYCLOAK_URL_REALM=${VUE_APP_KEYCLOAK_URL_REALM}
            - VUE_APP_KEYCLOAK_CLIENT_ID=${VUE_APP_KEYCLOAK_CLIENT_ID}
            - VUE_APP_BPM_URL=${VUE_APP_BPM_URL}
            - VUE_APP_FORM_IO_API_URL=${VUE_APP_FORM_IO_API_URL}
            - VUE_APP_FORM_IO_RESOURCE_ID=${VUE_APP_FORM_IO_RESOURCE_ID}
            - VUE_APP_FORM_IO_REVIEWER_ID=${VUE_APP_FORM_IO_REVIEWER_ID}
            - VUE_APP_FORM_IO_REVIEWER=${VUE_APP_FORM_IO_REVIEWER}
            - VUE_APP_FORM_FLOW_API_URL=${VUE_APP_FORM_FLOW_API_URL}
            - VUE_APP_FORM_FLOW_URL=${VUE_APP_FORM_FLOW_URL}
            - VUE_APP_FORMIO_ROLES=${VUE_APP_FORMIO_ROLES}
